import {BottomTabs, DrawerComponent} from '../Components/index';
import AdminKPIs from '../Screens/App/AdminKPIs';
import CommPostById from '../Screens/App/CommPostById';
import CreateCommPost from '../Screens/App/CreateCommPost';
import MySubscription from '../Screens/App/MySubscription';
import {
  ArtistProfile,
  Artists,
  ArtistStats,
  Bundles,
  BuySubscription,
  Call,
  ChangePassword,
  ChatDetails,
  ChatListing,
  EditProfile,
  Explore,
  FanDashboard,
  FreeTrial,
  JoinCompetition,
  JoinCompetitionAsFan,
  LanguageSettings,
  Live,
  MyCompetetions,
  Notifications,
  NotificationsSettings,
  PasswordUpdated,
  PaymentGateway,
  PostsListing,
  ProfileViewSubscription,
  RecentTransactions,
  Recommendation,
  RecordedLive,
  SelectArtistsForCompetition,
  Settings,
  StartLive,
  SubscriptionPlan,
  SuccessfulAccessPayment,
  SuccessfulPayment,
  TopStreams,
  UnlockAccess,
  UpcomingCompetitions,
  UserDataDisplay,
  UserProfile,
  WebViewScreen,
  Withdraw,
  CommunityScreen,
} from '../Screens/index';

export default [
  {id: '1', name: 'Drawer', Screen: DrawerComponent},
  {id: '1', name: 'BottomTabs', Screen: BottomTabs},
  {id: '3', name: 'Notifications', Screen: Notifications},
  {id: '5', name: 'Settings', Screen: Settings},
  {id: '6', name: 'TopStreams', Screen: TopStreams},
  {id: '7', name: 'Artists', Screen: Artists},
  {id: '8', name: 'SubscriptionPlan', Screen: SubscriptionPlan},
  {id: '9', name: 'ArtistProfile', Screen: ArtistProfile},
  {id: '10', name: 'NotificationsSettings', Screen: NotificationsSettings},
  {id: '11', name: 'ChangePassword', Screen: ChangePassword},
  {id: '12', name: 'BuySubscription', Screen: BuySubscription},
  {id: '12', name: 'ProfileViewSubscription', Screen: ProfileViewSubscription},
  {id: '12', name: 'PaymentGateway', Screen: PaymentGateway},
  {id: '12', name: 'SuccessfulPayment', Screen: SuccessfulPayment},
  {id: '12', name: 'Explore', Screen: Explore},
  {id: '12', name: 'UnlockAccess', Screen: UnlockAccess},
  {id: '12', name: 'SuccessfulAccessPayment', Screen: SuccessfulAccessPayment},
  {id: '13', name: 'FreeTrial', Screen: FreeTrial},
  {id: '14', name: 'Live', Screen: Live},
  {id: '15', name: 'PasswordUpdated', Screen: PasswordUpdated},
  {id: '16', name: 'EditProfile', Screen: EditProfile},
  {id: '17', name: 'ArtistStats', Screen: ArtistStats},
  {id: '18', name: 'UserProfile', Screen: UserProfile},
  {id: '19', name: 'UserDataDisplay', Screen: UserDataDisplay},
  {id: '20', name: 'StartLive', Screen: StartLive},
  {id: '21', name: 'FanDashboard', Screen: FanDashboard},
  {id: '22', name: 'Recommendation', Screen: Recommendation},
  {id: '23', name: 'RecentTransactions', Screen: RecentTransactions},
  {id: '24', name: 'ChatListing', Screen: ChatListing},
  {id: '25', name: 'ChatDetails', Screen: ChatDetails},
  {id: '26', name: 'PostsListing', Screen: PostsListing},
  {id: '27', name: 'Bundles', Screen: Bundles},
  {id: '28', name: 'Call', Screen: Call},
  {id: '29', name: 'Withdraw', Screen: Withdraw},
  {id: '30', name: 'WebViewScreen', Screen: WebViewScreen},
  {id: '31', name: 'LanguageSettings', Screen: LanguageSettings},
  {
    id: '32',
    name: 'SelectArtistsForCompetition',
    Screen: SelectArtistsForCompetition,
  },
  {id: '34', name: 'UpcomingCompetitions', Screen: UpcomingCompetitions},
  {id: '34', name: 'MyCompetetions', Screen: MyCompetetions},
  {id: '35', name: 'JoinCompetitionAsFan', Screen: JoinCompetitionAsFan},
  {id: '36', name: 'JoinCompetition', Screen: JoinCompetition},
  {id: '37', name: 'RecordedLive', Screen: RecordedLive},
  {id: '38', name: 'MySubscription', Screen: MySubscription},
  {id: '39', name: 'AdminKPIs', Screen: AdminKPIs},
  {id: '40', name: 'Community', Screen: CommunityScreen},
  {id: '41', name: 'CommPostById', Screen: CommPostById},
  {id: '42', name: 'CreateComPost', Screen: CreateCommPost},
];
